apiVersion: v1
kind: Pod

metadata:
  name: jenkins-pod
  namespace: jenkins
  labels:
    app: jenkins-pod

spec:
  serviceAccountName: jenkins-sa

  imagePullSecrets:
    - name: ghcr-secret

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload
                operator: In
                values:
                  - wnode1

  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 1000

  containers:
    - name: jenkins-server
      image: ghcr.io/truelykh/jenkins:1.0

      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375

      command:
        - /bin/bash
        - -c

      args:
        - |
          apt-get update
          apt-get install -y curl

          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

          install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

          rm -f kubectl

          exec /usr/bin/tini -- /usr/local/bin/jenkins

      ports:
        - containerPort: 8080
          name: admin

        - containerPort: 50000
          name: agent

      resources:
        requests:
          cpu: 350m
          memory: 768Mi

        limits:
          cpu: 1000m
          memory: 1.5Gi

      volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home

    - name: docker
      image: docker:27-dind

      securityContext:
        privileged: true

      args:
        - --insecure-registry=nexus-svc.nexus.svc.cluster.local:8082
        - --insecure-registry=192.168.41.20:8082

      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""

      ports:
        - containerPort: 2375
          name: docker

      resources:
        requests:
          cpu: 350m
          memory: 768Mi

        limits:
          cpu: 1000m
          memory: 1.5Gi

  volumes:
    - name: jenkins-data
      persistentVolumeClaim:
        claimName: jenkins-pvc
