apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  namespace: tomcat
  labels:
    app: tomcat
spec:
  serviceAccountName: tomcat-sa
  containers:
    - name: tomcat
      image: tomcat:9.0
      ports:
        - containerPort: 8080
          name: http
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 500m
      volumeMounts:
        - name: tomcat-data
          mountPath: /usr/local/tomcat/webapps
  volumes:
    - name: tomcat-data
      persistentVolumeClaim:
        claimName: tomcat-pvc
  restartPolicy: Always
