apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  namespace: tomcat
  labels:
    app.kubernetes.io/name: tomcat
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - name: http
      port: 8080
      targetPort: 8080
