apiVersion: v1
kind: Namespace
metadata:
  name: storeapp
  labels:
    name: storeapp
    app.kubernetes.io/part-of: storeapp
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    name: nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: jenkins
---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus
  labels:
    name: nexus
---
apiVersion: v1
kind: Namespace
metadata:
  name: tomcat
  labels:
    name: tomcat
