apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: storeapp
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: storeapp
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
