apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: storeapp
    app.kubernetes.io/component: ui

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: frontend

    spec:
      imagePullSecrets:
        - name: nexus-registry-secret

      nodeSelector:
        workload: wnode1

      containers:
        - name: frontend
          image: frontend-placeholder
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80
              name: http

          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 250m
              memory: 128Mi
